import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import path from 'path';
import fs from 'fs';

const app = express();
app.use(cors());
app.use(express.json({ limit: '2mb' }));
fs.mkdirSync(path.resolve('uploads'), { recursive: true });
app.use('/uploads', express.static(path.resolve('uploads')));

const PORT = Number(process.env.PORT || 5000);
const MONGODB_URI = process.env.MONGODB_URI;
const JWT_SECRET = process.env.JWT_SECRET;
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || '1d';
if (!MONGODB_URI || !JWT_SECRET) throw new Error('Application configuration is incomplete');

const { Schema } = mongoose;
const roles = ['CUSTOMER','BRANCH_STAFF','ADMIN'];
const vehicleStatuses = ['AVAILABLE','RESERVED','RENTED','MAINTENANCE'];
const bookingStatuses = ['RESERVED','PICKED_UP','RETURNED','CANCELLED'];
const addOnTypes = ['GPS','INSURANCE','DRIVER'];

const userSchema = new Schema({name:{type:String,required:true,trim:true},email:{type:String,required:true,unique:true,lowercase:true,trim:true},passwordHash:{type:String,required:true},role:{type:String,enum:roles,default:'CUSTOMER'},branchId:{type:Schema.Types.ObjectId,ref:'Branch',default:null}},{timestamps:true});
const branchSchema = new Schema({branchId:{type:String,required:true,unique:true,trim:true},name:{type:String,required:true,trim:true},location:{type:String,required:true,trim:true},city:{type:String,required:true,trim:true}},{timestamps:true});
branchSchema.index({branchId:1},{unique:true});
const vehicleSchema = new Schema({branchId:{type:Schema.Types.ObjectId,ref:'Branch',required:true},type:{type:String,enum:['CAR','BIKE'],required:true},name:{type:String,required:true,trim:true},make:{type:String,required:true,trim:true},model:{type:String,required:true,trim:true},photos:[String],perDayRate:{type:Number,required:true,min:0},permittedKilometers:{type:Number,required:true,min:0},extraKilometerCharge:{type:Number,required:true,min:0},fuelType:{type:String,enum:['PETROL','DIESEL','ELECTRIC'],default:'PETROL'},fuelTankCapacity:{type:Number,min:0,default:0},status:{type:String,enum:vehicleStatuses,default:'AVAILABLE'}},{timestamps:true});
vehicleSchema.index({branchId:1});
const bookingSchema = new Schema({customerId:{type:Schema.Types.ObjectId,ref:'User',required:true},vehicleId:{type:Schema.Types.ObjectId,ref:'Vehicle',required:true},startDate:{type:Date,required:true},endDate:{type:Date,required:true},status:{type:String,enum:bookingStatuses,default:'RESERVED'},baseAmount:{type:Number,default:0},addOnAmount:{type:Number,default:0},adjustmentAmount:{type:Number,default:0},totalAmount:{type:Number,default:0},selectedAddOns:[{type:Schema.Types.ObjectId,ref:'AddOn'}],cancellationCharge:{type:Number,default:0}},{timestamps:true});
bookingSchema.index({customerId:1}); bookingSchema.index({vehicleId:1,startDate:1,endDate:1});
const inspectionSchema = new Schema({bookingId:{type:Schema.Types.ObjectId,ref:'Booking',required:true},stage:{type:String,enum:['PICKUP','RETURN'],required:true},odometer:{type:Number,required:true,min:0},fuelLevel:{type:Number,required:true,min:0,max:100},damageNotes:{type:String,default:''},damageCharge:{type:Number,default:0,min:0},fuelCharge:{type:Number,default:0},extraKilometers:{type:Number,default:0,min:0},extraKilometerCharge:{type:Number,default:0,min:0},fuelAdjustmentType:{type:String,enum:['CHARGE','CREDIT','NONE'],default:'NONE'},photos:[String]},{timestamps:true});
const addOnSchema = new Schema({type:{type:String,enum:addOnTypes,required:true,unique:true},label:{type:String,required:true},pricePerDay:{type:Number,required:true,min:0},active:{type:Boolean,default:true}},{timestamps:true});
const fuelRateSchema = new Schema({city:{type:String,required:true},fuelType:{type:String,enum:['PETROL','DIESEL'],required:true},pricePerLitre:{type:Number,required:true,min:0},effectiveFrom:{type:Date,required:true}},{timestamps:true});

const User=mongoose.model('User',userSchema),Branch=mongoose.model('Branch',branchSchema),Vehicle=mongoose.model('Vehicle',vehicleSchema),Booking=mongoose.model('Booking',bookingSchema),Inspection=mongoose.model('Inspection',inspectionSchema),AddOn=mongoose.model('AddOn',addOnSchema),FuelRate=mongoose.model('FuelRate',fuelRateSchema);
class AppError extends Error{constructor(status,message,code='REQUEST_ERROR'){super(message);this.status=status;this.errorCode=code}}
const fail=(s,m,c)=>{throw new AppError(s,m,c)};
function validateId(id,label='ID'){if(!mongoose.isValidObjectId(id))fail(400,`${label} is invalid`,'VALIDATION_ERROR')}
function auth(req,_res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return next(new AppError(401,'Sign in to continue','AUTH_REQUIRED'));const p=jwt.verify(h.slice(7),JWT_SECRET);User.findById(p.sub).select('-passwordHash').then(u=>{if(!u)return next(new AppError(401,'Your session is no longer valid','AUTH_INVALID'));req.user=u;next()}).catch(()=>next(new AppError(401,'Your session is no longer valid','AUTH_INVALID')))}catch{next(new AppError(401,'Your session is no longer valid','AUTH_INVALID'))}}
const permit=(...a)=>(req,_res,next)=>a.includes(req.user.role)?next():next(new AppError(403,'You do not have permission for this action','FORBIDDEN'));
const scope=(branchId,user)=>user.role==='ADMIN'||String(branchId)===String(user.branchId);
function parseWindow(start,end){const s=new Date(start),e=new Date(end);if(isNaN(s)||isNaN(e))fail(400,'Please enter valid pickup and return times','VALIDATION_ERROR');if(s>=e)fail(400,'Return time must be after pickup time','VALIDATION_ERROR');if(s.getMinutes()||e.getMinutes()||s.getSeconds()||e.getSeconds())fail(400,'Pickup and return times must use one-hour intervals','VALIDATION_ERROR');return[s,e]}
const overlap=(s,e)=>({startDate:{$lt:e},endDate:{$gt:s},status:{$in:['RESERVED','PICKED_UP']}});
async function available(branchId,s,e){const vs=await Vehicle.find({branchId,status:{$ne:'MAINTENANCE'}}).lean();if(!vs.length)return[];const bs=await Booking.find({vehicleId:{$in:vs.map(v=>v._id)},...overlap(s,e)}).select('vehicleId').lean();const blocked=new Set(bs.map(b=>String(b.vehicleId)));return vs.filter(v=>!blocked.has(String(v._id)))}
const upload=multer({dest:path.resolve('uploads')});

app.get('/api/health',(_q,r)=>r.json({success:true,message:'OK'}));
app.post('/api/auth/register',async(req,res,next)=>{try{const{name,email,password}=req.body;if(!name||!email||!password)fail(400,'Name, email and password are required','VALIDATION_ERROR');if(password.length<6)fail(400,'Password must be at least 6 characters','VALIDATION_ERROR');if(await User.findOne({email:email.toLowerCase().trim()}))fail(409,'An account with this email already exists','DUPLICATE_RECORD');const u=await User.create({name,email,passwordHash:await bcrypt.hash(password,12),role:'CUSTOMER'});res.status(201).json({success:true,data:{user:{id:u._id,name:u.name,email:u.email,role:u.role},token:jwt.sign({sub:u._id.toString(),role:u.role},JWT_SECRET,{expiresIn:JWT_EXPIRES_IN})}})}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const{email,password}=req.body;if(!email||!password)fail(400,'Email and password are required','VALIDATION_ERROR');const u=await User.findOne({email:email.toLowerCase().trim()});if(!u||!(await bcrypt.compare(password,u.passwordHash)))fail(401,'Invalid email or password','AUTH_INVALID');res.json({success:true,data:{user:{id:u._id,name:u.name,email:u.email,role:u.role,branchId:u.branchId},token:jwt.sign({sub:u._id.toString(),role:u.role,branchId:u.branchId?.toString()||null},JWT_SECRET,{expiresIn:JWT_EXPIRES_IN})}})}catch(e){next(e)}});

app.get('/api/branches',auth,async(_q,res,next)=>{try{res.json({success:true,data:await Branch.find().sort({name:1})})}catch(e){next(e)}});
app.post('/api/branches',auth,permit('ADMIN'),async(req,res,next)=>{try{const{branchId,name,location}=req.body;if(!branchId||!name||!location)fail(400,'Branch ID, branch name and location are required','VALIDATION_ERROR');const b=await Branch.create({branchId:branchId.trim(),name,location,city:location.trim()});res.status(201).json({success:true,message:'Branch created successfully',data:b})}catch(e){next(e)}});
app.put('/api/branches/:id',auth,permit('ADMIN'),async(req,res,next)=>{try{validateId(req.params.id,'Branch ID');const b=await Branch.findByIdAndUpdate(req.params.id,{...req.body,city:req.body.location||req.body.city},{new:true,runValidators:true});if(!b)fail(404,'Branch not found','NOT_FOUND');res.json({success:true,data:b})}catch(e){next(e)}});
app.delete('/api/branches/:id',auth,permit('ADMIN'),async(req,res,next)=>{try{validateId(req.params.id,'Branch ID');if(await Vehicle.exists({branchId:req.params.id}))fail(409,'Branch cannot be deleted while vehicles are assigned to it','BUSINESS_RULE_CONFLICT');const b=await Branch.findByIdAndDelete(req.params.id);if(!b)fail(404,'Branch not found','NOT_FOUND');res.json({success:true,message:'Branch deleted successfully'})}catch(e){next(e)}});

app.get('/api/vehicles',auth,async(req,res,next)=>{try{const f={};if(req.user.role==='BRANCH_STAFF')f.branchId=req.user.branchId;if(req.query.branchId)f.branchId=req.query.branchId;res.json({success:true,data:await Vehicle.find(f).populate('branchId','branchId name location city').sort({createdAt:-1})})}catch(e){next(e)}});
app.post('/api/vehicles',auth,permit('ADMIN','BRANCH_STAFF'),upload.array('photos',8),async(req,res,next)=>{try{const b=req.body,branchId=req.user.role==='BRANCH_STAFF'?req.user.branchId:b.branchId;if(!branchId||!b.type||!b.name||!b.make||!b.model||b.perDayRate===undefined||b.permittedKilometers===undefined||b.extraKilometerCharge===undefined)fail(400,'Required vehicle details are missing','VALIDATION_ERROR');if(!scope(branchId,req.user))fail(403,'You cannot manage another branch','FORBIDDEN');const v=await Vehicle.create({...b,branchId,perDayRate:Number(b.perDayRate),permittedKilometers:Number(b.permittedKilometers),extraKilometerCharge:Number(b.extraKilometerCharge),fuelTankCapacity:Number(b.fuelTankCapacity||0),photos:(req.files||[]).map(f=>`/uploads/${f.filename}`)});res.status(201).json({success:true,message:'Vehicle added successfully',data:v})}catch(e){next(e)}});
app.put('/api/vehicles/:id',auth,permit('ADMIN','BRANCH_STAFF'),upload.array('photos',8),async(req,res,next)=>{try{validateId(req.params.id,'Vehicle ID');const v=await Vehicle.findById(req.params.id);if(!v)fail(404,'Vehicle not found','NOT_FOUND');if(!scope(v.branchId,req.user))fail(403,'You cannot manage another branch','FORBIDDEN');const b=req.body;const updates={...b};for(const k of ['perDayRate','permittedKilometers','extraKilometerCharge','fuelTankCapacity'])if(updates[k]!==undefined)updates[k]=Number(updates[k]);delete updates.photos;if((req.files||[]).length)updates.photos=req.files.map(f=>`/uploads/${f.filename}`);else updates.photos=v.photos;if(req.user.role==='BRANCH_STAFF')delete updates.branchId;const out=await Vehicle.findByIdAndUpdate(req.params.id,updates,{new:true,runValidators:true});res.json({success:true,message:'Vehicle updated successfully',data:out})}catch(e){next(e)}});
app.delete('/api/vehicles/:id',auth,permit('ADMIN','BRANCH_STAFF'),async(req,res,next)=>{try{validateId(req.params.id,'Vehicle ID');const v=await Vehicle.findById(req.params.id);if(!v)fail(404,'Vehicle not found','NOT_FOUND');if(!scope(v.branchId,req.user))fail(403,'You cannot manage another branch','FORBIDDEN');if(await Booking.exists({vehicleId:v._id,status:{$in:['RESERVED','PICKED_UP']}}))fail(409,'Vehicle cannot be deleted while it has an active booking','BUSINESS_RULE_CONFLICT');await Vehicle.findByIdAndDelete(v._id);res.json({success:true,message:'Vehicle deleted successfully'})}catch(e){next(e)}});
app.get('/api/vehicles/search',async(req,res,next)=>{try{const{branchId,startDate,endDate,type}=req.query;if(!branchId||!startDate||!endDate)fail(400,'Branch, pickup time and return time are required','VALIDATION_ERROR');validateId(branchId,'Branch ID');const[s,e]=parseWindow(startDate,endDate);let vs=await available(branchId,s,e);if(type)vs=vs.filter(v=>v.type===String(type).toUpperCase());res.json({success:true,data:{availableQuantity:vs.length,status:vs.length?'AVAILABLE':'SOLD_OUT',vehicles:vs}})}catch(e){next(e)}});

app.get('/api/pricing/add-ons',auth,async(_q,res,next)=>{try{res.json({success:true,data:await AddOn.find({active:true}).sort({type:1})})}catch(e){next(e)}});
app.post('/api/pricing/add-ons',auth,permit('ADMIN','BRANCH_STAFF'),async(req,res,next)=>{try{const{type,label,pricePerDay}=req.body;if(!addOnTypes.includes(type)||!label||pricePerDay===undefined)fail(400,'Add-on details are required','VALIDATION_ERROR');const a=await AddOn.findOneAndUpdate({type},{type,label,pricePerDay:Number(pricePerDay),active:true},{upsert:true,new:true,runValidators:true});res.json({success:true,data:a})}catch(e){next(e)}});
app.post('/api/pricing/fuel-rates',auth,permit('ADMIN'),async(req,res,next)=>{try{const{city,fuelType,pricePerLitre,effectiveFrom}=req.body;if(!city||!fuelType||pricePerLitre===undefined||!effectiveFrom)fail(400,'Fuel rate details are required','VALIDATION_ERROR');res.status(201).json({success:true,data:await FuelRate.create({city,fuelType,pricePerLitre:Number(pricePerLitre),effectiveFrom:new Date(effectiveFrom)})})}catch(e){next(e)}});
app.get('/api/pricing/fuel-rates',auth,async(req,res,next)=>{try{res.json({success:true,data:await FuelRate.find(req.query.city?{city:req.query.city}:{}).sort({effectiveFrom:-1})})}catch(e){next(e)}});

app.post('/api/bookings',auth,permit('CUSTOMER'),async(req,res,next)=>{try{const{vehicleId,startDate,endDate,addOns=[]}=req.body;validateId(vehicleId,'Vehicle ID');const[s,e]=parseWindow(startDate,endDate);const v=await Vehicle.findById(vehicleId);if(!v)fail(404,'Vehicle not found','NOT_FOUND');if(!(await available(v.branchId,s,e)).some(x=>String(x._id)===String(v._id)))fail(409,'Vehicle is sold out for the selected time slot','SOLD_OUT');const days=Math.max(1,Math.ceil((e-s)/86400000));const extras=await AddOn.find({_id:{$in:addOns},active:true}).lean();const base=v.perDayRate*days,extra=extras.reduce((n,a)=>n+a.pricePerDay*days,0);const b=await Booking.create({customerId:req.user._id,vehicleId,startDate:s,endDate:e,baseAmount:base,addOnAmount:extra,totalAmount:base+extra,selectedAddOns:extras.map(a=>a._id)});res.status(201).json({success:true,data:await b.populate(['vehicleId','selectedAddOns'])})}catch(e){next(e)}});
app.get('/api/customers/:id/bookings',auth,async(req,res,next)=>{try{validateId(req.params.id,'Customer ID');if(req.user.role!=='ADMIN'&&String(req.user._id)!==String(req.params.id))fail(403,'You can only view your own rentals','FORBIDDEN');res.json({success:true,data:await Booking.find({customerId:req.params.id}).populate('vehicleId').populate('selectedAddOns').sort({startDate:-1})})}catch(e){next(e)}});
app.post('/api/bookings/:id/cancel',auth,permit('CUSTOMER'),async(req,res,next)=>{try{validateId(req.params.id,'Booking ID');const b=await Booking.findById(req.params.id);if(!b)fail(404,'Booking not found','NOT_FOUND');if(String(b.customerId)!==String(req.user._id))fail(403,'You can only cancel your own booking','FORBIDDEN');if(b.status!=='RESERVED')fail(409,'Only reserved bookings can be cancelled','BUSINESS_RULE_CONFLICT');const h=(new Date(b.startDate)-new Date())/3600000;const c=h>48?0:h>=24?b.totalAmount*.25:b.totalAmount*.5;b.cancellationCharge=c;b.adjustmentAmount=-c;b.totalAmount=Math.max(0,b.totalAmount-c);b.status='CANCELLED';await b.save();res.json({success:true,data:{booking:b,cancellationCharge:c}})}catch(e){next(e)}});

app.post('/api/bookings/:id/pickup',auth,permit('BRANCH_STAFF','ADMIN'),upload.array('photos',8),async(req,res,next)=>{try{validateId(req.params.id,'Booking ID');const b=await Booking.findById(req.params.id).populate('vehicleId');if(!b)fail(404,'Booking not found','NOT_FOUND');if(!scope(b.vehicleId.branchId,req.user))fail(403,'You cannot process another branch booking','FORBIDDEN');if(b.status!=='RESERVED')fail(409,'This booking is not ready for pickup','BUSINESS_RULE_CONFLICT');if(req.body.odometer===undefined||req.body.fuelLevel===undefined)fail(400,'Pickup details are required','VALIDATION_ERROR');if(await Inspection.exists({bookingId:b._id,stage:'PICKUP'}))fail(409,'Pickup inspection already exists','BUSINESS_RULE_CONFLICT');await Inspection.create({bookingId:b._id,stage:'PICKUP',odometer:Number(req.body.odometer),fuelLevel:Number(req.body.fuelLevel),damageNotes:req.body.damageNotes||'',photos:(req.files||[]).map(f=>`/uploads/${f.filename}`)});b.status='PICKED_UP';await b.save();b.vehicleId.status='RENTED';await b.vehicleId.save();res.json({success:true,data:b})}catch(e){next(e)}});
app.post('/api/bookings/:id/return',auth,permit('BRANCH_STAFF','ADMIN'),upload.array('photos',8),async(req,res,next)=>{try{validateId(req.params.id,'Booking ID');const b=await Booking.findById(req.params.id).populate('vehicleId');if(!b)fail(404,'Booking not found','NOT_FOUND');if(!scope(b.vehicleId.branchId,req.user))fail(403,'You cannot process another branch booking','FORBIDDEN');if(b.status!=='PICKED_UP')fail(409,'This booking is not ready for return','BUSINESS_RULE_CONFLICT');const p=await Inspection.findOne({bookingId:b._id,stage:'PICKUP'});if(!p)fail(409,'Pickup inspection is required before return','BUSINESS_RULE_CONFLICT');const od=Number(req.body.odometer),fuel=Number(req.body.fuelLevel),damage=Number(req.body.damageCharge||0);if(!Number.isFinite(od)||!Number.isFinite(fuel))fail(400,'Return details are required','VALIDATION_ERROR');if(od<p.odometer)fail(400,'Return odometer cannot be less than pickup odometer','VALIDATION_ERROR');const travelled=od-p.odometer,extraKm=Math.max(travelled-b.vehicleId.permittedKilometers,0),extraCharge=extraKm*b.vehicleId.extraKilometerCharge;const branch=await Branch.findById(b.vehicleId.branchId);let fuelAdj=0,type='NONE';if(branch&&b.vehicleId.fuelType!=='ELECTRIC'&&b.vehicleId.fuelTankCapacity>0){const rate=await FuelRate.findOne({city:branch.city,fuelType:b.vehicleId.fuelType}).sort({effectiveFrom:-1});if(rate&&fuel!==p.fuelLevel){fuelAdj=Number(((Math.abs(fuel-p.fuelLevel)/100*b.vehicleId.fuelTankCapacity)*rate.pricePerLitre).toFixed(2));type=fuel<p.fuelLevel?'CHARGE':'CREDIT';if(type==='CREDIT')fuelAdj=-fuelAdj}}const inspection=await Inspection.create({bookingId:b._id,stage:'RETURN',odometer:od,fuelLevel:fuel,damageNotes:req.body.damageNotes||'',damageCharge:damage,fuelCharge:fuelAdj,extraKilometers:extraKm,extraKilometerCharge:extraCharge,fuelAdjustmentType:type,photos:(req.files||[]).map(f=>`/uploads/${f.filename}`)});b.adjustmentAmount=damage+extraCharge+fuelAdj;b.totalAmount=Math.max(0,b.totalAmount+b.adjustmentAmount);b.status='RETURNED';await b.save();b.vehicleId.status='AVAILABLE';await b.vehicleId.save();res.json({success:true,data:{booking:b,inspection,settlement:{travelledKm:travelled,extraKm,extraCharge,fuelAdjustment:fuelAdj,damageCharge:damage,finalTotal:b.totalAmount}}})}catch(e){next(e)}});
app.get('/api/staff/bookings',auth,permit('BRANCH_STAFF','ADMIN'),async(req,res,next)=>{try{const ids=await Vehicle.find(req.user.role==='ADMIN'?{}:{branchId:req.user.branchId}).distinct('_id');res.json({success:true,data:await Booking.find({vehicleId:{$in:ids},...(req.query.status?{status:req.query.status}:{})}).populate('customerId','name email').populate('vehicleId').sort({startDate:1})})}catch(e){next(e)}});
app.get('/api/admin/reports/utilization',auth,permit('ADMIN','BRANCH_STAFF'),async(req,res,next)=>{try{const branches=await Branch.find(req.user.role==='ADMIN'?(req.query.branchId?{_id:req.query.branchId}:{}):{_id:req.user.branchId});const from=req.query.from?new Date(req.query.from):new Date(new Date().getFullYear(),0,1),to=req.query.to?new Date(req.query.to):new Date(),days=Math.max(1,Math.ceil((to-from)/86400000));const rows=[];for(const br of branches){const ids=await Vehicle.find({branchId:br._id}).distinct('_id');const bs=await Booking.find({vehicleId:{$in:ids},status:{$in:['PICKED_UP','RETURNED']},startDate:{$lt:to},endDate:{$gt:from}});const booked=bs.reduce((s,b)=>s+Math.max(0,(Math.min(to,new Date(b.endDate))-Math.max(from,new Date(b.startDate)))/86400000),0),capacity=Math.max(1,ids.length*days),revenue=bs.reduce((s,b)=>s+b.totalAmount,0);rows.push({branchId:br._id,branch:br.name,city:br.location,vehicles:ids.length,bookedVehicleDays:Number(booked.toFixed(2)),utilizationRate:Number((booked/capacity*100).toFixed(2)),revenue:Number(revenue.toFixed(2))})}res.json({success:true,data:{branches:rows,totals:{revenue:rows.reduce((s,r)=>s+r.revenue,0),utilizationRate:rows.length?Number((rows.reduce((s,r)=>s+r.utilizationRate,0)/rows.length).toFixed(2)):0}}})}catch(e){next(e)}});
app.get('/api/admin/dashboard',auth,permit('ADMIN','BRANCH_STAFF'),async(req,res,next)=>{try{const f=req.user.role==='BRANCH_STAFF'?{branchId:req.user.branchId}:{};const vehicleCount=await Vehicle.countDocuments(f),availableCount=await Vehicle.countDocuments({...f,status:'AVAILABLE'}),rented=await Vehicle.countDocuments({...f,status:'RENTED'}),maintenance=await Vehicle.countDocuments({...f,status:'MAINTENANCE'}),ids=await Vehicle.find(f).distinct('_id'),bookings=await Booking.countDocuments({vehicleId:{$in:ids}}),rev=await Booking.aggregate([{$match:{vehicleId:{$in:ids},status:'RETURNED'}},{$group:{_id:null,total:{$sum:'$totalAmount'}}}]);res.json({success:true,data:{vehicleCount,available:availableCount,rented,maintenance,bookings,revenue:rev[0]?.total||0}})}catch(e){next(e)}});

app.use((err,_req,res,_next)=>{const status=err.status||500;const code=err.errorCode||(err.name==='ValidationError'?'VALIDATION_ERROR':'INTERNAL_ERROR');res.status(status).json({success:false,message:status>=500?'Request could not be completed':err.message,errorCode:code})});
await mongoose.connect(MONGODB_URI);app.listen(PORT,()=>console.log(`Vehicle Rental API listening on port ${PORT}`));
