import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CalendarDays,Clock3,MapPin,Search, Bike, CarFront, LogOut, LayoutDashboard, ClipboardList, Wrench, BarChart3, Building2, Settings2, Plus, X, CheckCircle2, AlertCircle, Menu, Camera, Fuel, Gauge, ReceiptText} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const dateTime=d=>new Date(d).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
async function api(path,opts={}){
  const token=localStorage.getItem('vrm_token');
  const headers={...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})};
  const res=await fetch(`${API}${path}`,{...opts,headers});
  const data=await res.json().catch(()=>({success:false,message:'Invalid server response'}));
  if(!res.ok) throw new Error(data.message||'Request failed'); return data;
}

function Brand({compact=false}){return <div className="brand"><div className="brand-mark">V</div>{!compact&&<div><strong>VROOM</strong><span>vehicle rental operations</span></div>}</div>}
function Status({children}){return <span className={`status status-${String(children).toLowerCase()}`}>{String(children).replaceAll('_',' ')}</span>}
function Toast({error,success}){if(!error&&!success)return null; return <div className={`toast ${error?'danger':'success'}`}>{error?<AlertCircle size={17}/>:<CheckCircle2 size={17}/>}<span>{error||success}</span></div>}

function Auth({onLogin}){
  const [mode,setMode]=useState('login'); const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async e=>{e.preventDefault();setError('');setBusy(true);try{const r=await api(mode==='login'?'/auth/login':'/auth/register',{method:'POST',body:JSON.stringify(form)});localStorage.setItem('vrm_token',r.data.token);onLogin(r.data.user)}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <div className="auth-shell"><div className="auth-side"><Brand/><div className="auth-copy"><p className="eyebrow">RENT. RIDE. RETURN.</p><h1>A calmer way to manage every rental.</h1><p>Search by real-time availability, manage branch operations, and settle every return with one connected system.</p><div className="auth-detail"><span>01</span><div><b>One-hour booking slots</b><p>Clear pickup and drop-off windows with live inventory.</p></div></div><div className="auth-detail"><span>02</span><div><b>Inspection-led settlement</b><p>Fuel, kilometers and damage are calculated at return.</p></div></div></div></div><div className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><div><p className="eyebrow">ACCOUNT ACCESS</p><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p className="muted">{mode==='login'?'Sign in to continue to your rental workspace.':'Customer accounts are created here. Staff and Admin accounts are provisioned by the system administrator.'}</p></div>{mode==='register'&&<Field label="Full name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your full name" required/></Field>}<Field label="Email"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com" required/></Field><Field label="Password"><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••" minLength="6" required/></Field><Toast error={error}/><button className="btn primary full" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button><button type="button" className="link-btn" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?"New customer? Create an account":"Already registered? Sign in"}</button></form></div></div>
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}

function Shell({user,onLogout,children,title,nav,setPage,page}){return <div className="app-shell"><aside className="sidebar"><Brand/><div className="role-chip">{user.role.replace('_',' ')}{user.branchId&&<span>Branch account</span>}</div><nav>{nav.map(n=><button key={n.key} className={page===n.key?'active':''} onClick={()=>setPage(n.key)}>{n.icon}{n.label}</button>)}</nav><div className="sidebar-foot"><div className="user-mini"><div className="avatar">{user.name?.slice(0,1).toUpperCase()}</div><div><b>{user.name}</b><span>{user.email}</span></div></div><button className="logout" onClick={onLogout}><LogOut size={17}/> Sign out</button></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">VROOM / {user.role.replace('_',' ')}</p><h1>{title}</h1></div><button className="mobile-menu"><Menu/></button></header><div className="content">{children}</div></main></div>}

function Customer({user,onLogout}){
  const [page,setPage]=useState('search'); const [branches,setBranches]=useState([]); const [addons,setAddons]=useState([]); const [history,setHistory]=useState([]); const [results,setResults]=useState(null); const [selected,setSelected]=useState(null); const [toast,setToast]=useState({}); const [form,setForm]=useState({branchId:'',type:'BIKE',startDate:'',startTime:'10:00',endDate:'',endTime:'18:00'}); const [busy,setBusy]=useState(false);
  const load=async()=>{try{const b=await api('/branches');setBranches(b.data);const a=await api('/pricing/add-ons');setAddons(a.data);const h=await api(`/customers/${user.id}/bookings`);setHistory(h.data)}catch(e){setToast({error:e.message})}};
  useEffect(()=>{load()},[]);
  const search=async e=>{e.preventDefault();setToast({});setBusy(true);try{const data=await api(`/vehicles/search?branchId=${form.branchId}&startDate=${encodeURIComponent(`${form.startDate}T${form.startTime}:00`)}&endDate=${encodeURIComponent(`${form.endDate}T${form.endTime}:00`)}&type=${form.type}`);setResults(data.data)}catch(e){setToast({error:e.message});setResults(null)}finally{setBusy(false)}};
  const book=async(v)=>{try{const data=await api('/bookings',{method:'POST',body:JSON.stringify({vehicleId:v._id,startDate:`${form.startDate}T${form.startTime}:00`,endDate:`${form.endDate}T${form.endTime}:00`,addOns:addons.filter(a=>a._selected).map(a=>a._id)})});setToast({success:'Booking confirmed successfully.'});setSelected(null);await load();setPage('history');return data}catch(e){setToast({error:e.message})}};
  const toggleAddon=id=>setAddons(addons.map(a=>a._id===id?{...a,_selected:!a._selected}:a));
  const cancel=async(id)=>{try{await api(`/bookings/${id}/cancel`,{method:'POST'});setToast({success:'Booking cancelled and policy applied.'});await load()}catch(e){setToast({error:e.message})}};
  const nav=[{key:'search',label:'Book a vehicle',icon:<Search size={18}/>},{key:'history',label:'My rentals',icon:<ClipboardList size={18}/> }];
  return <Shell user={user} onLogout={onLogout} title={page==='search'?'Find your next ride':'My rentals'} nav={nav} setPage={setPage} page={page}><Toast error={toast.error} success={toast.success}/>{page==='search'?<><section className="search-panel glass"><div className="search-intro"><p className="eyebrow">Go For A Ride Now</p><h2>Book your ride here</h2></div><form className="search-grid" onSubmit={search}><Field label="Branch"><select value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})} required><option value="">Select branch</option>{branches.map(b=><option key={b._id} value={b._id}>{b.name} · {b.city}</option>)}</select></Field><Field label="Vehicle type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="BIKE">Bike</option><option value="CAR">Car</option></select></Field><Field label="Pickup date"><input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} required/></Field><Field label="Pickup time"><select value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}>{hours().map(h=><option key={h}>{h}</option>)}</select></Field><Field label="Return date"><input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})} required/></Field><Field label="Return time"><select value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}>{hours().map(h=><option key={h}>{h}</option>)}</select></Field><button className="btn primary search-btn" disabled={busy}><Search size={17}/>{busy?'Checking…':'Search availability'}</button></form></section>{results&&<section className="results"><div className="section-head"><div><p className="eyebrow">{results.availableQuantity} AVAILABLE</p><h2>{results.status==='SOLD_OUT'?'Sold out for this window':'Available vehicles'}</h2></div>{results.status==='SOLD_OUT'&&<span className="sold">SOLD OUT</span>}</div><div className="vehicle-grid">{results.vehicles.map(v=><VehicleCard key={v._id} v={v} onSelect={()=>setSelected(v)}/>)}</div></section>}</>:<section><div className="section-head"><div><p className="eyebrow">BOOKING HISTORY</p><h2>Your rentals</h2></div></div><div className="history-list">{history.length?history.map(b=><BookingCard key={b._id} b={b} onCancel={()=>cancel(b._id)}/>):<Empty title="No rentals yet" text="Your confirmed bookings will appear here."/>}</div></section>}{selected&&<BookingModal vehicle={selected} addons={addons} onToggleAddon={toggleAddon} onClose={()=>setSelected(null)} onConfirm={()=>book(selected)} form={form}/>}</Shell>
}
function hours(){return Array.from({length:14},(_,i)=>`${String(i+8).padStart(2,'0')}:00`)}
function VehicleCard({v,onSelect}){return <article className="vehicle-card"><div className="vehicle-photo">{v.photos?.[0]?<img src={v.photos[0]} alt=""/>:<div className="photo-placeholder">{v.type==='CAR'?<CarFront size={42}/>:<Bike size={42}/>}</div>}<span className="vehicle-type">{v.type}</span></div><div className="vehicle-body"><div><p className="eyebrow">{v.make}</p><h3>{v.name}</h3><p className="muted">{v.model} · {v.permittedKilometers} km included</p></div><div className="vehicle-row"><strong>{money(v.perDayRate)}<small>/day</small></strong><button className="btn secondary" onClick={onSelect}>Book</button></div></div></article>}
function BookingModal({vehicle,addons,onToggleAddon,onClose,onConfirm,form}){const days=Math.max(1,Math.ceil((new Date(`${form.endDate}T${form.endTime}`)-new Date(`${form.startDate}T${form.startTime}`))/86400000));const selected=addons.filter(a=>a._selected);const base=vehicle.perDayRate*days;const extra=selected.reduce((s,a)=>s+a.pricePerDay*days,0);return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><p className="eyebrow">CONFIRM RENTAL</p><h2>{vehicle.name}</h2><p className="muted">{dateTime(`${form.startDate}T${form.startTime}`)} → {dateTime(`${form.endDate}T${form.endTime}`)}</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="addon-grid">{addons.map(a=><button key={a._id} className={`addon ${a._selected?'selected':''}`} onClick={()=>onToggleAddon(a._id)}><span>{a.label}</span><b>{a.pricePerDay?`${money(a.pricePerDay)}/day`:'Configured by staff'}</b></button>)}</div><div className="summary-box"><div><span>Rental</span><b>{money(base)}</b></div><div><span>Add-ons</span><b>{money(extra)}</b></div><div className="total"><span>Total</span><b>{money(base+extra)}</b></div></div><button className="btn primary full" onClick={onConfirm}>Confirm booking</button></div></div>}
function BookingCard({b,onCancel}){return <article className="booking-card"><div className="booking-main"><div className="mini-vehicle">{b.vehicleId?.photos?.[0]?<img src={b.vehicleId.photos[0]} alt=""/>:<Bike size={28}/>}</div><div><p className="eyebrow">{b.vehicleId?.make}</p><h3>{b.vehicleId?.name}</h3><p className="muted">{dateTime(b.startDate)} → {dateTime(b.endDate)}</p></div></div><div className="booking-meta"><Status>{b.status}</Status><b>{money(b.totalAmount)}</b>{b.status==='RESERVED'&&<button className="btn ghost danger-text" onClick={onCancel}>Cancel</button>}</div></article>}
function Empty({title,text}){return <div className="empty"><ClipboardList size={28}/><h3>{title}</h3><p>{text}</p></div>}

function Operations({user,onLogout,admin=false}){
 const [page,setPage]=useState(admin?'dashboard':'dashboard'); const [data,setData]=useState({vehicleCount:0,available:0,rented:0,maintenance:0,bookings:0,revenue:0}); const [vehicles,setVehicles]=useState([]); const [bookings,setBookings]=useState([]); const [branches,setBranches]=useState([]); const [toast,setToast]=useState({}); const [modal,setModal]=useState(null);
 const load=async()=>{try{const [d,v,b,br]=await Promise.all([api('/admin/dashboard'),api('/vehicles'),api('/staff/bookings'),api('/branches')]);setData(d.data);setVehicles(v.data);setBookings(b.data);setBranches(br.data)}catch(e){setToast({error:e.message})}}; useEffect(()=>{load()},[]);
 const submitVehicle=async(form)=>{try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>{if(k!=='photos')fd.append(k,v)});Array.from(form.photos||[]).forEach(f=>fd.append('photos',f));await api('/vehicles',{method:'POST',body:fd});setToast({success:'Vehicle added to the fleet.'});setModal(null);load()}catch(e){setToast({error:e.message})}};
 const pickup=async b=>{const od=prompt('Enter pickup odometer (km):');const fuel=prompt('Enter pickup fuel level (%):');if(od===null||fuel===null)return;try{const fd=new FormData();fd.append('odometer',od);fd.append('fuelLevel',fuel);await api(`/bookings/${b._id}/pickup`,{method:'POST',body:fd});setToast({success:'Pickup inspection recorded.'});load()}catch(e){setToast({error:e.message})}};
 const ret=async b=>{const od=prompt('Enter return odometer (km):');const fuel=prompt('Enter return fuel level (%):');const damage=prompt('Enter damage charge (₹), 0 if none:','0');if(od===null||fuel===null||damage===null)return;try{const fd=new FormData();fd.append('odometer',od);fd.append('fuelLevel',fuel);fd.append('damageCharge',damage);await api(`/bookings/${b._id}/return`,{method:'POST',body:fd});setToast({success:'Return inspection recorded and settlement calculated.'});load()}catch(e){setToast({error:e.message})}};
 const nav=admin?[{key:'dashboard',label:'Overview',icon:<LayoutDashboard size={18}/>},{key:'branches',label:'Branches',icon:<Building2 size={18}/>},{key:'fleet',label:'Fleet',icon:<Bike size={18}/>},{key:'bookings',label:'Bookings',icon:<ClipboardList size={18}/>},{key:'reports',label:'Reports',icon:<BarChart3 size={18}/>},{key:'pricing',label:'Pricing & fuel',icon:<Settings2 size={18}/> }]:[{key:'dashboard',label:'Operations',icon:<LayoutDashboard size={18}/>},{key:'fleet',label:'Local fleet',icon:<Bike size={18}/>},{key:'bookings',label:'Bookings',icon:<ClipboardList size={18}/>}];
 return <Shell user={user} onLogout={onLogout} title={page==='dashboard'?(admin?'Management overview':'Branch operations'):page==='fleet'?'Fleet management':page==='bookings'?'Booking operations':page==='branches'?'Branches':page==='reports'?'Utilization & revenue':'Pricing & fuel' } nav={nav} setPage={setPage} page={page}><Toast error={toast.error} success={toast.success}/>{page==='dashboard'&&<Dashboard data={data} admin={admin}/>} {page==='fleet'&&<Fleet vehicles={vehicles} onAdd={()=>setModal('vehicle')}/>} {page==='bookings'&&<Bookings bookings={bookings} onPickup={pickup} onReturn={ret}/>} {page==='branches'&&<Branches branches={branches} onSaved={load}/>} {page==='reports'&&<Reports/>}{page==='pricing'&&<Pricing/>}{modal==='vehicle'&&<VehicleForm admin={admin} branches={branches} user={user} onClose={()=>setModal(null)} onSubmit={submitVehicle}/>}</Shell>
}
function Dashboard({data,admin}){return <><section className="kpi-grid"><Kpi label="Fleet" value={data.vehicleCount} meta="Total vehicles" icon={<Bike/>}/><Kpi label="Available" value={data.available} meta="Ready to rent" icon={<CheckCircle2/>}/><Kpi label="Rented" value={data.rented} meta="On road now" icon={<Clock3/>}/><Kpi label="Revenue" value={money(data.revenue)} meta="Returned bookings" icon={<ReceiptText/>}/></section><section className="split"><div className="panel"><div className="section-head"><div><p className="eyebrow">CONTROL CENTRE</p><h2>{admin?'System health':'Today at your branch'}</h2></div></div><div className="ops-list"><div><Gauge/><span>Bookings tracked</span><b>{data.bookings}</b></div><div><Wrench/><span>Maintenance</span><b>{data.maintenance}</b></div><div><BarChart3/><span>Utilization</span><b>{data.vehicleCount?Math.round((data.rented/data.vehicleCount)*100):0}%</b></div></div></div><div className="panel quote"><p className="eyebrow">WORKFLOW</p><h3>Every rental follows the same chain.</h3><p>Reserved → Picked-up → Returned. Inspection data becomes the source for the final settlement.</p></div></section></>}
function Kpi({label,value,meta,icon}){return <div className="kpi glass"><div className="kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>}
function Fleet({vehicles,onAdd}){return <section><div className="section-head"><div><p className="eyebrow">FLEET REGISTER</p><h2>Vehicles</h2></div><button className="btn primary" onClick={onAdd}><Plus size={17}/> Add vehicle</button></div><div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Branch</th><th>Type</th><th>Rate</th><th>Included KM</th><th>Status</th></tr></thead><tbody>{vehicles.map(v=><tr key={v._id}><td><div className="table-vehicle"><div className="table-thumb">{v.photos?.[0]?<img src={v.photos[0]} alt=""/>:<Bike size={18}/>}</div><div><b>{v.name}</b><span>{v.make} · {v.model}</span></div></div></td><td>{v.branchId?.name||'—'}</td><td>{v.type}</td><td>{money(v.perDayRate)}/day</td><td>{v.permittedKilometers} km <span className="muted">· +{money(v.extraKilometerCharge)}/km</span></td><td><Status>{v.status}</Status></td></tr>)}</tbody></table></div></section>}
function Bookings({bookings,onPickup,onReturn}){return <section><div className="section-head"><div><p className="eyebrow">OPERATIONS QUEUE</p><h2>Bookings</h2></div></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Vehicle</th><th>Window</th><th>Status</th><th>Amount</th><th></th></tr></thead><tbody>{bookings.map(b=><tr key={b._id}><td><b>{b.customerId?.name}</b><span>{b.customerId?.email}</span></td><td>{b.vehicleId?.name}</td><td>{dateTime(b.startDate)}<br/><span className="muted">to {dateTime(b.endDate)}</span></td><td><Status>{b.status}</Status></td><td>{money(b.totalAmount)}</td><td className="actions">{b.status==='RESERVED'&&<button className="btn small secondary" onClick={()=>onPickup(b)}>Pickup</button>}{b.status==='PICKED_UP'&&<button className="btn small primary" onClick={()=>onReturn(b)}>Return</button>}</td></tr>)}</tbody></table></div></section>}
function Branches({branches,onSaved}){const [name,setName]=useState(''),[city,setCity]=useState(''); const save=async()=>{try{await api('/branches',{method:'POST',body:JSON.stringify({name,city})});setName('');setCity('');onSaved()}catch(e){alert(e.message)}};return <section><div className="section-head"><div><p className="eyebrow">BRANCH NETWORK</p><h2>Branches</h2></div><div className="inline-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Branch name"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City"/><button className="btn primary" onClick={save}><Plus size={17}/> Add</button></div></div><div className="branch-grid">{branches.map(b=><div className="panel branch-card" key={b._id}><Building2 size={21}/><h3>{b.name}</h3><p><MapPin size={15}/>{b.city}</p></div>)}</div></section>}
function Reports(){const [r,setR]=useState(null);useEffect(()=>{api('/admin/reports/utilization').then(x=>setR(x.data)).catch(()=>{})},[]);return <section><div className="section-head"><div><p className="eyebrow">REPORTING MODULE</p><h2>Utilization & revenue</h2></div></div>{r&&<><div className="report-kpis"><Kpi label="Network revenue" value={money(r.totals.revenue)} meta="Returned rentals" icon={<ReceiptText/>}/><Kpi label="Avg. utilization" value={`${r.totals.utilizationRate}%`} meta="Across branches" icon={<BarChart3/>}/></div><div className="table-wrap"><table><thead><tr><th>Branch</th><th>Vehicles</th><th>Booked days</th><th>Utilization</th><th>Revenue</th></tr></thead><tbody>{r.branches.map(x=><tr key={x.branchId}><td><b>{x.branch}</b><span>{x.city}</span></td><td>{x.vehicles}</td><td>{x.bookedVehicleDays}</td><td>{x.utilizationRate}%</td><td>{money(x.revenue)}</td></tr>)}</tbody></table></div></>}</section>}
function Pricing(){const [addOns,setAddOns]=useState([]),[fuel,setFuel]=useState({city:'Bengaluru',fuelType:'PETROL',pricePerLitre:'',effectiveFrom:''});const load=async()=>setAddOns((await api('/pricing/add-ons')).data);useEffect(()=>{load()},[]);const saveAdd=async(a)=>{await api('/pricing/add-ons',{method:'POST',body:JSON.stringify(a)});load()};const saveFuel=async()=>{await api('/pricing/fuel-rates',{method:'POST',body:JSON.stringify(fuel)});alert('Fuel rate saved')};return <section className="split"><div className="panel"><p className="eyebrow">ADD-ONS</p><h2>Company-provided extras</h2>{addOns.map(a=><div className="setting-row" key={a._id}><div><b>{a.label}</b><span>{a.type}</span></div><div className="inline-form"><input defaultValue={a.pricePerDay} onBlur={e=>saveAdd({...a,pricePerDay:Number(e.target.value)})}/><span>/day</span></div></div>)}</div><div className="panel"><p className="eyebrow">FUEL RATES</p><h2>Settlement configuration</h2><Field label="City"><input value={fuel.city} onChange={e=>setFuel({...fuel,city:e.target.value})}/></Field><Field label="Fuel type"><select value={fuel.fuelType} onChange={e=>setFuel({...fuel,fuelType:e.target.value})}><option>PETROL</option><option>DIESEL</option></select></Field><Field label="Price per litre"><input type="number" min="0" value={fuel.pricePerLitre} onChange={e=>setFuel({...fuel,pricePerLitre:e.target.value})}/></Field><Field label="Effective from"><input type="date" value={fuel.effectiveFrom} onChange={e=>setFuel({...fuel,effectiveFrom:e.target.value})}/></Field><button className="btn primary" onClick={saveFuel}>Save fuel rate</button></div></section>}
function VehicleForm({branches,user,onClose,onSubmit}){const [form,setForm]=useState({branchId:user.role==='BRANCH_STAFF'?user.branchId:'',type:'BIKE',name:'',make:'',model:'',perDayRate:'',permittedKilometers:'',extraKilometerCharge:'',fuelType:'PETROL',fuelTankCapacity:'',status:'AVAILABLE',photos:[]});return <div className="modal-backdrop"><div className="modal wide"><div className="modal-head"><div><p className="eyebrow">FLEET ENTRY</p><h2>Add vehicle</h2><p className="muted">Enter values from the company's operational vehicle form.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="form-grid">{user.role==='ADMIN'&&<Field label="Branch"><select value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}>{branches.map(b=><option key={b._id} value={b._id}>{b.name}</option>)}</select></Field>}<Field label="Type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>BIKE</option><option>CAR</option></select></Field><Field label="Vehicle name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Make"><input value={form.make} onChange={e=>setForm({...form,make:e.target.value})}/></Field><Field label="Model"><input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></Field><Field label="Per-day rate"><input type="number" value={form.perDayRate} onChange={e=>setForm({...form,perDayRate:e.target.value})}/></Field><Field label="Included KM"><input type="number" value={form.permittedKilometers} onChange={e=>setForm({...form,permittedKilometers:e.target.value})}/></Field><Field label="Extra KM charge"><input type="number" value={form.extraKilometerCharge} onChange={e=>setForm({...form,extraKilometerCharge:e.target.value})}/></Field><Field label="Fuel type"><select value={form.fuelType} onChange={e=>setForm({...form,fuelType:e.target.value})}><option>PETROL</option><option>DIESEL</option><option>ELECTRIC</option></select></Field><Field label="Tank capacity (L)"><input type="number" value={form.fuelTankCapacity} onChange={e=>setForm({...form,fuelTankCapacity:e.target.value})}/></Field><Field label="Vehicle photos"><input type="file" accept="image/*" multiple onChange={e=>setForm({...form,photos:e.target.files})}/></Field></div><div className="modal-foot"><button className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" onClick={()=>onSubmit(form)}>Save vehicle</button></div></div></div>}
function App(){const [user,setUser]=useState(null);useEffect(()=>{try{const u=localStorage.getItem('vrm_user');if(u)setUser(JSON.parse(u))}catch{}},[]);const login=u=>{localStorage.setItem('vrm_user',JSON.stringify(u));setUser(u)};const logout=()=>{localStorage.removeItem('vrm_token');localStorage.removeItem('vrm_user');setUser(null)};if(!user)return <Auth onLogin={login}/>;return user.role==='CUSTOMER'?<Customer user={user} onLogout={logout}/>:<Operations user={user} onLogout={logout} admin={user.role==='ADMIN'}/>}

createRoot(document.getElementById('root')).render(<App/>);
